stages:
  - deploy-queue
  - deploy-client

deploy-titan:
  script:
  - cd Deployment && ./deploy-titan.sh $CI_COMMIT_TAG
  tags:
  - Titan
  stage: deploy-client
  only:
  - tags

deploy-summitdev:
  script:
  - cd Deployment && ./deploy-summitdev.sh $CI_COMMIT_TAG
  tags:
  - SummitDev
  stage: deploy-client
  only:
  - tags

deploy-summit:
  script:
  - cd Deployment && ./deploy-summit.sh $CI_COMMIT_TAG
  tags:
  - Summit
  stage: deploy-client
  only:
  - tags

deploy-openstack:
  script:
  - cd Deployment && ./deploy-openstack.sh $CI_COMMIT_TAG
  tags:
  - OpenStack
  stage: deploy-queue
  only:
  - tags
  artifacts:
    paths:
      - Deployment/artifacts/ContainerBuilderKey