stages:
  - deploy

deploy-titan:
  script:
  - ./deploy-titan.sh $CI_COMMIT_TAG
  tags:
  - titan
  stage: deploy
  only:
  - tags

deploy-summitdev:
  script:
  - ./deploy-summitdev.sh $CI_COMMIT_TAG
  tags:
  - ppc64le
  stage: deploy
  only:
  - tags

deploy-openstack:
  script:
  - ./deploy-openstack.sh $CI_COMMIT_TAG
  tags:
  - openstack
  stage: deploy
  only:
  - tags